Vagrant.configure('2') do |config|
    config.vm.define "kerberos" do |kerberos|
        kerberos.vm.box = "centos/7"
        kerberos.vm.hostname = "kerberos"
        kerberos.vm.network "private_network",ip: "#{ENV['KERBEROS_IP']}"     
        kerberos.vm.provider "virtualbox" do |v|
            v.memory = 1024
            v.cpus = 1
      end
    end 
end 

