Vagrant.configure('2') do |config|
    config.vm.define "admin" do |admin|
        admin.vm.box = "centos/7"
        admin.vm.hostname = "admin"
        admin.vm.network "private_network",ip: "#{ENV['ADMIN_IP']}"     
        admin.vm.provider "virtualbox" do |v|
            v.memory = 2048
            v.cpus = 2
        end
      admin.vm.provision "shell", path: "scripts/admin.sh"
    end 

    config.vm.define "prometheus" do |prometheus|
        prometheus.vm.box = "centos/7"
        prometheus.vm.hostname = "prometheus"
        prometheus.vm.network "private_network",ip: "#{ENV['PROMETHEUS_IP']}"     
        prometheus.vm.provider "virtualbox" do |v|
            v.memory = 1024
            v.cpus = 1
        end
        prometheus.vm.provision "shell", path: "scripts/prometheus.sh"
    end 

    config.vm.define "grafana" do |grafana|
        grafana.vm.box = "centos/7"
        grafana.vm.hostname = "grafana"
        grafana.vm.network "private_network",ip: "#{ENV['GRAFANA_IP']}"     
        grafana.vm.provider "virtualbox" do |v|
            v.memory = 1024
            v.cpus = 1
        end
      grafana.vm.provision "shell", path: "scripts/grafana.sh"
    end 
end 

