scrape_configs:
  - job_name: "broker-jmx-metrics"
    # metrics_path defaults to '/'
    static_configs:
      - targets: ["192.168.56.131:8080","192.168.56.132:8080","192.168.56.133:8080"]
  - job_name: "zk-jmx-metrics"
    # metrics_path defaults to '/'
    static_configs:
      - targets: ["192.168.56.121:8081"]
  - job_name: "zk-prometheus-metrics"
    # metrics_path defaults to '/'
    static_configs:
      - targets: ["192.168.56.121:7000"]