Vagrant.configure('2') do |config|
    config.vm.define "ksqldb" do |ksqldb|
        ksqldb.vm.box = "centos/7"
        ksqldb.vm.hostname = "ksqldb"
        ksqldb.vm.network "private_network",ip: "#{ENV['KSQLDB_IP']}"
        ksqldb.vm.provider "virtualbox" do |v|
            v.memory = 4096
            v.cpus = 2
        end
        ksqldb.vm.provision "shell", path: "scripts/ksqldb.sh", args: "#{ENV['KSQLDB_IP']} '192.168.56.131:9092'"
    end 
end